#
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: r1
#          uri: lb://USERMS
#          predicates:
#            - Path= /users/**
#        - id: r2
#          uri: lb://ORGANISATIONMS
#          predicates:
#            - Path= /organistions/**

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true